// This header file has been automatically generated from the shaders in this directory.
// It is generated by the embed_shaders.hs script.
#pragma once

constexpr const char *TEXTURE_FRAG = R"---(#version 330 core
out vec4 fragColour;

in vec3 outColour;
in vec2 outTexCoord;

uniform sampler2D textureSampler;

void main() {
    fragColour = texture(textureSampler, outTexCoord) * vec4(outColour, 1.0);
}
)---";

constexpr const char *TEXTURE_VERT = R"---(#version 330 core
layout (location = 0) in vec3 pos;
layout (location = 1) in vec3 col;
layout (location = 2) in vec2 texCoord;

out vec3 outColour;
out vec2 outTexCoord;

void main() {
    gl_Position = vec4(pos, 1);
    outColour = col;
    outTexCoord = texCoord;
}
)---";

