// This header file has been automatically generated from the shaders in this directory.
// It is generated by the embed_shaders.hs script.
#pragma once

constexpr const char *TRIANGLE_VERT = R"---(#version 330 core
layout (location = 0) in vec3 pos;

void main() {
    gl_Position = vec4(pos, 1.0);
}
)---";

constexpr const char *TRIANGLE_FRAG = R"---(#version 330 core
out vec4 colour;

void main() {
    colour = vec4(1.0f, 0.5f, 0.3f, 1.0f);
}
)---";
