{-
Small program to embed the contents of my shaders into an includable .h file.

This is necessary because C++ does not have an easy way of embedding the
contents of a file into source at compile time. The standard way of doing it
seems to be to write a small program to do it manually.

Now, you are probably asking "why are you using haskell for scripts and not python?"
The answer is because I think it's funny
-}

import System.Directory
import Data.List
import Data.Char

shaderDir :: FilePath
shaderDir = "src/shaders/"

preamble :: String
preamble = "// This header file has been automatically generated from the shaders in this directory.\n"
    ++ "// It is generated by the embed_shaders.hs script.\n"
    ++ "#pragma once\n\n"

isShaderFile :: FilePath -> Bool
isShaderFile str = any (`isSuffixOf` str) [".frag", ".vert", ".glsl"]

filenameToVarname :: String -> String
filenameToVarname = map (\c -> if c == '.' then '_' else toUpper c)

-- Takes a string (containing the contents of a file) and converts it to a C++ constant declaration
stringToConstDecl varName contents =
    "constexpr const char *" ++ varName ++ " = R\"---(" ++ contents ++ ")---\";\n"

getShaderFiles :: IO [FilePath]
getShaderFiles = do
    filenames <- getDirectoryContents shaderDir
    return $ filter isShaderFile filenames

genShaderDecl :: FilePath -> IO String
genShaderDecl filename = do
    contents <- readFile (shaderDir ++ filename)
    return $ stringToConstDecl (filenameToVarname filename) contents

main :: IO ()
main = do
    files <- getShaderFiles
    declarations <- mapM genShaderDecl files
    let fileContents = preamble ++ unlines declarations
    writeFile (shaderDir ++ "shaders.h") fileContents
